### ISSUE TITLE
The game font is forced to Unicode when recurrent-1~6 is loaded

### ISSUE THREAD

**Issue by LittleMiserY** [KameiB/rl-language-packs#1] opened 2024-11-20 11:09 UTC
Hi, do you remember me?   I recently used your mod to translate the content of RLCraft, and I've run into a problem.   When I loaded the translated resource pack into the game, the game font was forced to change to Unicode.   After checking, I found that the problem was with files named recurrent-1 to recurrent-6.   I don't know what to do now.

**Comment by KameiB** [comment] 2024-11-21 04:06
Hi!
So are you telling me that if you delete those Recurrent-x files, the game font comes back to normal?

**Comment by LittleMiserY** [comment] 2024-11-21 14:57
Yes, by removing this section, I can disable Unicode fonts in the language Settings.  However, it cannot be disabled when this section is loaded.  Also, using en_us.lang doesn't cause any problems, but it does when using zh_cn.lang

**Comment by LittleMiserY** [comment] 2024-11-21 15:02
I don't know what caused it.  The following is a resourcepacks that I do about the Recurrent-x section.
[问题部分.zip](https://github.com/user-attachments/files/17847784/default.zip)
When the recurent-x file is not loaded：

https://github.com/user-attachments/assets/d2fb1b00-2c3c-4bde-a561-c196ceaf2b9a


when loading the Recurrent-x file：

https://github.com/user-attachments/assets/785cf3e3-4142-4683-88ed-972c056ac5ec

**Comment by KameiB** [comment] 2024-11-21 16:10
Hmmm I can't test right now, but do me a favor.

Each recurrent-x file has a maximum of 23,000 lang keys right?
Can you try and divide each recurrent-x file in 2 files?
So:
[Original]
recurrent-1/lang/zh_cn.lang (23,000 lang keys)
[Modified]
recurrent-1-1/lang/zh_cn.lang (first 11,500 lang keys)
recurrent-1-2/lang/zh_cn.lang (last 11,500 lang keys)

I think your unicode characters may double the file length, and minecraft doesn't like it.
I used the maximum of 23,000 because it was near the file lenght limit.

Thanks for the additional information, and please let me know your results!

**Comment by KameiB** [comment] 2024-11-24 18:31
After further discussion via Discord, we found a solution.

The problem is a Vanilla bug.
The "Unicode Fix" mod specifically solves this bug.

**[Modrinth]**
https://modrinth.com/mod/unicode-fix
**[CurseForge]** 
https://www.curseforge.com/minecraft/mc-mods/unicode-fix
Marking as Solved.

**Closed as completed by KameiB** 2024-11-24 18:31 UTC
